"""add state column to files

Revision ID: 3feeefc4e8e8
Revises: efb17bbdead1
Create Date: 2026-08-06 07:16:55.925920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3feeefc4e8e8'
down_revision: Union[str, Sequence[str], None] = 'efb17bbdead1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('state', sa.String(length=20), server_default='scheduled', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'state')
    # ### end Alembic commands ###
